---
driver:
  name: vagrant
  #winrm_transport: :plaintext

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-10
    driver_config:
      box: StefanScherer/windows_10
      customize:
        clipboard: 'bidirectional'

suites:
  - name: default
    os_type: windows
    shell_type: powershell
    run_list:
      - recipe[win-10-admin::default]
